<a href="https://colab.research.google.com/github/pbluest-rong/NLU_ML/blob/main/Lab_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **Task 1: Python Programming**

Task 1.1

In [ ]:
# Task 1.1
L = []
n = int(input("Nhap n: "))
for i in range(n):
  x = int(input("Nhap x: "))
  L.append(x)
print(L)

import numpy as np
L.sort()
print(L)
L.sort(reverse=True)
max = np.max(L)
min = np.min(L)
sum = np.sum(L)
print(L,max,min,sum)

positive_count = 0
negative_count = 0
for i in L:
  if i > 0:
        positive_count+=1
  elif i < 0:
        negative_count+=1
print(positive_count,negative_count)

Nhap n: 3
Nhap x: 2
Nhap x: 6
Nhap x: 3
[2, 6, 3]
[2, 3, 6]
[6, 3, 2] 6 2 11
3 0


Task 1.2

In [ ]:
# Task 1.2
def S(n):
 if n == 1:
  return 1
 else:
    temp = 1;
    for i in range(1,n+1):
      temp *= i
    return S(n-1) + temp;
print(S(3))

9


In [ ]:
()

Task 1.3

In [ ]:
#Task 1.3
# Account class: {name: String; email: String; country: String;
#                 friends: List<Account>; posts: List<Post>}
# Post class: {content: String; subject: String; likes: int}
# AccountManager: {accounts: List<Account>}

from abc import ABC, abstractmethod
import datetime

class Post:
  def __init__(self, subject, likes):
    self.subject = subject
    self.likes = likes
  def __str__(self):
    return f"{self.subject} - {self.likes}"

class Account(ABC):
  def __str__(self):
    return f"{self.name} - {self.email} - {self.country}"
  def __init__(self, name, email, country, friends=None, posts=None):
    self.name = name
    self.email = email
    self.country = country
    self.friends = friends if friends is not None else []
    self.posts = posts if posts is not None else []

  # find the account having the post with the highest likes from the list of friends.
  def _getMaxLikePostByFriend(self):
      res = None
      maxLike = 0
      if self.friends is not None:
        for f in self.friends:
          for p in f.posts:
            if p.likes > maxLike:
              maxLike = p.likes
              res = p
      return res

class VerifiedAccount(Account):
    def __init__(self, name, email, country, fromDate, friends=None, posts=None):
      super().__init__(name,email,country,friends,posts)
      self.__fromDate = fromDate
class NormalProduct(Account):
     def __init__(self, name, email, country, friends=None, posts=None):
      super().__init__(name,email,country,friends,posts)

class AccountManager:
  def __init__(self, accounts):
    self.accounts = accounts
  def __str__(self):
    res = []
    for i in self.accounts:
      res.append(str(i))
    return f"{res}"
  # key = false <= <10 post else true
  def groupAccountsByPostLike(self):
    trueGroup = []
    falseGroup = []
    for a in self.accounts:
      if len(a.posts) > 10:
        trueGroup.append(a)
      else:
        falseGroup.append(a)
    return {True: trueGroup, False: falseGroup}
  # get all accounts from a given country
  # descending: number of post, ascending: name
  def filterAccounts(self, country):
    group =  {a for a in self.accounts if a.country == country}
    sorted_list = sorted(group, key = lambda a: (-len(a.posts), a.name))
    return sorted_list

# Test
a1 = Account("Pblues", "pblues@gmail.com","VietNam",None, None)
friends = [a1]

p1 = Post("ML", 10)
p2 = Post("Mobile", 9)
p3 = Post("Web", 8)
posts =[p1,p2,p3]
a2 = VerifiedAccount("Phụng", "lungbaphe772003@gmail.com","VietNam",datetime.datetime.now(),friends, posts)
print(a2._getMaxLikePostByFriend())

accounts = [a1,a2]
manager = AccountManager(accounts)
print(manager)
for i in manager.groupAccountsByPostLike(): print(i)
for i in manager.filterAccounts("VN"): print(i)
for i in manager.filterAccounts("VietNam"): print(i)

None
['Pblues - pblues@gmail.com - VietNam', 'Phụng - lungbaphe772003@gmail.com - VietNam']
True
False
Phụng - lungbaphe772003@gmail.com - VietNam
Pblues - pblues@gmail.com - VietNam


## **Task 2: NumPy API**

Task 2.1

In [ ]:
# Task 2.1: arange.reshape
import numpy as np
arr = np.arange(10,26).reshape(16)
print(arr)
print(np.flip(arr))

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25]
[25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


Task 2.2

In [ ]:
# Task 2.2: tile
def task_2(arr, number_repetitions):
  return np.tile(arr, number_repetitions)
arr_2 = [1,2,3,4]
print(task_2(arr_2,3))

[1 2 3 4 1 2 3 4 1 2 3 4]


Task 2.3

In [ ]:
# Task 2.3:
arr_3 = [[ 0.42, 0.48, 0.32],
         [ 0.74, 0.58, 0.38],
         [ 0.51, 0.34, 0.15]]

arr_3 = np.array(arr_3)
arr_3[arr_3 > 0.5] = 0.5
print(arr_3)

[[0.42 0.48 0.32]
 [0.5  0.5  0.38]
 [0.5  0.34 0.15]]
